headerText = """https://github.com/codemicro/headers
Copyright (c) {{ .Year }}, codemicro and contributors
SPDX-License-Identifier: MIT
Filename: {{ .Filename }}"""

spec = [
    { regex = '^.+\.go', comment = "//" },
]

[options]
fullFilepath = true
